
export const Routes = {
    // pages
    Presentation: { path: "/" },
    DashboardOverview: { path: "/overview" },
    Investment: { path: "/investment/:id" },
    OrderOverview: { path: "/orderoverview" },
    Profile: { path: "/profile" },
    SpecialOffer: { path: "/specialoffer" },
    Ticket: { path: "/tiketss/:id" },
    DepositCRT: { path: "/depositcrts/:id" },
    Payouts: { path: "/payouts/:id" },
    StakeCRT: { path: "/stakecrt/:id" },
    Reinvest: { path: "/reinvest/:id" },
    Profits: { path: "/profits" },
    TransferCRT: { path: "/transfercrt" },
    Convert: { path: "/convert" },
    Exchange: { path: "/exchange" },
    Cryptonits: { path: "/cryptonits" },
    Referrals: { path: "/referrals" },
    Playroom: { path: "/playroom" },
    Transactions: { path: "/transactionss" },
    Settings: { path: "/settings" },
    Upgrade: { path: "/upgrade" },
    BootstrapTables: { path: "/tables/bootstrap-tabless" },
    Billing: { path: "/examples/billings" },
    Invoice: { path: "/examples/invoice" },
    Signin: { path: "/examples/sign-in" },
    Signup: { path: "/examples/sign-up" },
    ForgotPassword: { path: "/examples/forgot-password" },
    ResetPassword: { path: "/examples/reset-password" },
    Lock: { path: "/examples/lock" },
    NotFound: { path: "/examples/404" },
    ServerError: { path: "/examples/500" },
    Error: { path: "/error" },

    // docs
    DocsOverview: { path: "/documentation/overview" },
    DocsDownload: { path: "/documentation/download" },
    DocsQuickStart: { path: "/documentation/quick-start" },
    DocsLicense: { path: "/documentation/license" },
    DocsFolderStructure: { path: "/documentation/folder-structure" },
    DocsBuild: { path: "/documentation/build-tools" },
    DocsChangelog: { path: "/documentation/changelog" },

    // components
    Accordions: { path: "/components/accordionss" },
    Alerts: { path: "/components/alerts" },
    Badges: { path: "/components/badges" },
    Widgets: { path: "/widgets" },
    Breadcrumbs: { path: "/components/breadcrumbs" },
    Buttons: { path: "/components/buttons" },
    Forms: { path: "/components/forms" },
    Modals: { path: "/components/modals" },
    Navs: { path: "/components/navs" },
    Navbars: { path: "/components/navbars" },
    Pagination: { path: "/components/pagination" },
    Popovers: { path: "/components/popovers" },
    Progress: { path: "/components/progress" },
    Tables: { path: "/components/tables" },
    Tabs: { path: "/components/tabs" },
    Tooltips: { path: "/components/tooltips" },
    Toasts: { path: "/components/toasts" },
    WidgetsComponent: { path: "/components/widgets" }
};